// Autogenerated from Pigeon (v24.2.2), do not edit directly.
// See also: /pigeons/native_pitch_messages.dart

class NativePitchResultMessage {
  NativePitchResultMessage({
    required this.noteName,
    required this.frequency,
    required this.centsOffset,
    required this.midiNote,
  });

  String noteName;
  double frequency;
  double centsOffset;
  int midiNote;

  Object encode() {
    return <Object?>[
      noteName,
      frequency,
      centsOffset,
      midiNote,
    ];
  }

  static NativePitchResultMessage decode(Object result) {
    final values = result as List<Object?>;
    return NativePitchResultMessage(
      noteName: values[0]! as String,
      frequency: (values[1]! as num).toDouble(),
      centsOffset: (values[2]! as num).toDouble(),
      midiNote: values[3]! as int,
    );
  }
}
