// Autogenerated from Pigeon (v24.2.2), do not edit directly.
// See also: /pigeons/native_pitch_messages.dart

class NativePitchResultMessage {
  NativePitchResultMessage({
    required this.noteName,
    required this.frequency,
    required this.centsOffset,
    required this.midiNote,
  });

  String noteName;
  double frequency;
  double centsOffset;
  int midiNote;

  Object encode() {
    return <Object?>[
      noteName,
      frequency,
      centsOffset,
      midiNote,
    ];
  }

  static NativePitchResultMessage decode(Object result) {
    final values = result as List<Object?>;
    return NativePitchResultMessage(
      noteName: values[0]! as String,
      frequency: (values[1]! as num).toDouble(),
      centsOffset: (values[2]! as num).toDouble(),
      midiNote: values[3]! as int,
    );
  }

  static NativePitchResultMessage? tryDecode(Object? result) {
    if (result is! List<Object?> || result.length != 4) {
      return null;
    }
    final noteName = result[0];
    final frequency = result[1];
    final centsOffset = result[2];
    final midiNote = result[3];
    if (noteName is! String ||
        frequency is! num ||
        centsOffset is! num ||
        midiNote is! int) {
      return null;
    }
    return NativePitchResultMessage(
      noteName: noteName,
      frequency: frequency.toDouble(),
      centsOffset: centsOffset.toDouble(),
      midiNote: midiNote,
    );
  }
}
